# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Mesure',
                'verbose_name_plural': 'Mesures',
            },
        ),
        migrations.CreateModel(
            name='Measure_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Punt de mesura',
                'verbose_name_plural': 'Punts de mesura',
            },
        ),
        migrations.CreateModel(
            name='Type_measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_measure', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tipus de mesura',
                'verbose_name_plural': 'Tipus de mesures',
            },
        ),
        migrations.AddField(
            model_name='measure',
            name='measure_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.Measure_point'),
        ),
        migrations.AddField(
            model_name='measure',
            name='type_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.Type_measure'),
        ),
        migrations.AddField(
            model_name='measure',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
