# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.AlterField(
            model_name='measure_point',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.Area'),
        ),
    ]
