# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20180819_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_point',
            name='type_measure',
            field=models.CharField(blank=True, choices=[('fred', 'fred'), ('calent', 'calent')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='type_measure',
            field=models.CharField(blank=True, choices=[('fred', 'fred'), ('calent', 'calent')], max_length=15, null=True),
        ),
    ]
