# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20180819_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='type_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.Type_measure'),
        ),
        migrations.RemoveField(
            model_name='measure_point',
            name='type_measure',
        ),
        migrations.AddField(
            model_name='measure_point',
            name='type_measure',
            field=models.ManyToManyField(blank=True, to='control.Type_measure'),
        ),
    ]
