# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20180819_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_point',
            name='name',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
    ]
