# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20180820_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measure_point',
            options={'ordering': ['weight'], 'verbose_name': 'Punt de mesura', 'verbose_name_plural': 'Punts de mesura'},
        ),
        migrations.AddField(
            model_name='measure_point',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
