# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_auto_20180822_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_point',
            name='number',
            field=models.IntegerField(default='1', unique=True),
            preserve_default=False,
        ),
    ]
