# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_measure_point_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='status_OK',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
